print("Wsp bi- im jk")
print("anyways how is u doin?")
print("I'm Amy 🥺")
print("Feburary 10, 2025")
print("I am tryinng to learn how to code and in doing so to learn the basics of coding.")
print("I will make sure to spend some time everyday coding along, for a miminum of 10 minutes a day")
print("I'll be using the videos from replit 100 days of code, and Thonny applications in learnig the basics for now. Later on will use Phycharm and some other applications to continue learning the basics and even complexities of coding too! 😎")
print()
myName = input ("What is your name?: ")
myAge = input("How old are you? :")
print("Your fricking old fr")
aarvish = input("Is Aarvish on meth?: ")
print("OF COURSE HE IS LOL")
print()
print("So, you are")
print(myName)
print("and you are at a young old age of")
print(myAge)
print("And u understand Aarvish is on meth...")
print(aarvish)
print()
myName = input("Heyyy, btw what's your name again?: ")
print("ohh, got it!")
myLunch = input("What are u gonna be having for lunch?: ")
print(myName, "Your gonna have", myLunch, "for lunch huh? well np I'll pay for it!")
print()
print("Alr... now lets play a game")
food = input("Name a food > ")
plant = input("Name a plant, any plant > ")
cooking = input("Name any method of cooking > ")
burnedFood = input("what kind of food descibes burned food? > ")
scissors = input("rock, paper, ...? ")
print()
print("Well there u go.. your gonna have", food, "correct? Uhh", plant,"and", cooking, "oh yea with", burnedFood, "and", scissors, "as well")
print("and won")
print()
print("=== Your Adventure Simulator ===")
print("""You'll be asked a bunch of questions then we'll make you up an amazing syory with YOU as the star! 🤩""")
print()
name = input("Your name: ")
enemy = input("Your enemy's name: ")
superPower = input("Your Super power: ")
print()
print("Our story begins as our hero,", name, "approches a foreboding castle...")
print("Suddenly a bolt of lightning striked the grounds at the feet of", name)
print("'Our final bettle begins!' shouts the evil'", enemy, "clearly mising the fact that", name, "has the power of", superPower, "which means they'll win quite easily")
print()
print()
print("Ouu, oh, you've been given some", "\033[32m", "money", "\033[0m", "for being a good, good person.")
myName = input("What's your name again? Sry! I keep forgetting: ")
if myName == "Amy":
    print("\033[34m", "Well, lets get lunch!")
else:
    print("\033[31m", "Uhh, WHO THE HELL ARE YOU!?")
catsOrDogs = input("Are you a cat or a dog person? ")
if catsOrDogs == "Dogs":
    print("\033[36m", "OUU I AM TOO!")
else:
    print("cute!🥹")
print("\033[32m", "Marvel Movie Character Creator")
print("--")
yesOrNo = input("Do you like 'hanging around'?: ")
if yesOrNo == "No":
    print("Then you're not Spider-man")
else:
    print("Then you're Spider-Man")
yesOrNo = input("Do you have a 'gravelly' voice?: ")
if yesOrNo == "No":
    print("Aww, then you're not Korg")
else:
    print("Ouu, then you're Korg")
yesOrNo = input("Do you often feel 'Marvelous'?: ")
if yesOrNo == "Yes":
    print("Aha! You're Captain Marvel! Hi!")
else:
    print("Dang, You're not Captain Marvel. Hmm")
