print("😊 Custom Affirmation Generator 😇")
print("----------------------------")
print("You look nice today? 🤭 ")
print("Today you're going to make an impact and change on the world! 😮‍💨")
print("Keep on going! 😌")
print()
print("😩 Custom Curse Generator 😈")
print("-----------------------")
print("Alright Dumbahh. How's your insecurities? 😐")
print("Dude, lose my phone number 😑")
print("Not you again. Can you stop tapping your fingers on my keybaord please? 🙄")
print("Like Gawhd 🙄")